name = "FFTPreconditionedCG"
uuid = "0952d9b4-2cf0-4724-860a-ae82a6cf6f19"
version = "1.0.0-DEV"
authors = ["Xin Kai Lee <xin.lee18@imperial.ac.uk> and contributors"]

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
NVTX = "5da4648a-3479-48b8-97b9-01cb529c0a1f"
Oceananigans = "9e8cae18-63c1-5223-a75c-80ca9d6e9a09"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"

[sources]
Oceananigans = {rev = "xk-ss/distributed-cg-solver", url = "https://github.com/CliMA/Oceananigans.jl.git"}

[compat]
ArgParse = "1.2.0"
JLD2 = "0.5.13"
KernelAbstractions = "0.9.39"
MPI = "0.20.23"
NVTX = "1.0.1"
Roots = "2.2.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
